#!/data/data/com.termux/files/usr/bin/bash

G="\e[32m"
R="\e[31m"
Y="\e[01;33m"
N="\e[0m"

# Funkce pro zobrazení nápovědy
show_help() {
	echo -e "Usage: rename <${Y}filename${N}/${Y}s${N}>"
}

# Funkce pro zobrazení informací o verzi
show_version() {
	echo "rename v1.1"
	echo "by PhateValleyman"
	echo "Jonas.Ned@outlook.com"
}

# Funkce pro přejmenování souboru
rename_file() {
	local old_filename="$1"
	local new_filename="$2"

	if [ -e "$new_filename" ]; then
		echo -e "\"\e[01;33m$new_filename\e[0m\""
		read -p "already exists. Do you want to overwrite it? (y/n): " overwrite
		case "$overwrite" in
			[Yy]*)
				if mv -f -- "$old_filename" "$new_filename"; then
					echo -e "File \"${Y}$old_filename${N}\" renamed to \"${G}$new_filename${N}\""
				else
					echo -e "Failed to rename file \"${R}$old_filename${N}\""
					return 1
				fi
				;;
			*)
				echo -e "Rename ${Y}aborted${N}..."
				return 1
				;;
		esac
	else
		if mv -f -- "$old_filename" "$new_filename"; then
			echo -e "File \"${Y}$old_filename${N}\" renamed to \"${G}$new_filename${N}\""
		else
			echo -e "Failed to rename file \"${R}$old_filename${N}\""
			return 1
		fi
	fi
}

# Funkce pro zpracování argumentů příkazové řádky
process_arguments() {
	case "$1" in
		--help | -h | -?)
			show_help
			;;
		--version | -v)
			show_version
			;;
		*)
			if [ "$#" -lt 1 ] || [ ! -e "$1" ]; then
				show_help
				return 1
			fi
			local old_filename="$1"
			local new_filename
			read -ei "$old_filename" new_filename
			rename_file "$old_filename" "$new_filename"
			;;
	esac
}

# Volání funkce pro zpracování argumentů příkazové řádky
process_arguments "$@"
